# needed for postgresql 9.5 which currently works only on trusty
dist: trusty
sudo: required

# some interesting discussion about Postgresql 9.5 on travis (required by babayaga) https://github.com/travis-ci/travis-ci/issues/4264
language: java
script: ./gradlew check --info
jdk:
  - oraclejdk8
services:
  - postgresql
addons:
    postgresql: "9.5"

before_install:
# fixes gradlew requirements
   - chmod +x gradlew
# need to create our test database
before_script:
  - psql -c 'create database babayaga_tst;' -U postgres
  - psql -U postgres -c "CREATE USER test WITH PASSWORD 'test';"
  - psql -U postgres -c "GRANT ALL PRIVILEGES ON DATABASE babayaga_tst to test;"
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/